### ISSUE TITLE
steam username upload to mysal will be unintelligible text when using windows csgo dedicated server

### ISSUE THREAD

**Issue by LemonPAKA** [SQLMatches/API#11]
using InnoDB with utf8mb4_unicode_ci ( Mysql 5.6 with Ubuntu 16.04.6 LTS)
https://imgur.com/RhvoIqn
https://imgur.com/apRY3DL

**Comment by WardPearce** [comment]
Yea I'm gonna add unicode support when I have time.

**Comment by b3none** [comment]
@LemonPAKA I believe https://github.com/csgo-league deals with this issue.

**Comment by WardPearce** [comment]
Should of mentioned something.
Issues are not intended for advertising B3n.

But yeah his web panel is worth using if you want a uncreative copy of something.
