### ISSUE TITLE
No match detected

### ISSUE THREAD

**Issue by ManuXpy** [SQLMatches/API#15]
hello, the plugin apparently has it installed correctly but I don't see that it writes anything in the database, so all the fields are empty.

Add the plugin and the web (SM-Map-Statistics) and it works without problems, that's why I don't understand what I could do wrong. Thank you very much good work.

**Comment by WardPearce** [comment]
I'm assuming the database details have been added to databases.cfg? This is most likely a MySQL version issue, I'd recommend installing the latest version onto your web server. If this isn't the case, provide me with some error logs and I'll take a look.

**Comment by ManuXpy** [comment]
Solved, Thanks
