### ISSUE TITLE
sqlmatches.smx (SQLMatches): Could not find required plugin "sqlmatches_apistats"

### ISSUE THREAD

**Issue by rpkaul** [SQLMatches/API#19]
[SM] Listing 24 plugins:
  04 Failed "SQLMatches" (1.0.0) by The Doggy
  15 "SQLMatches API Stats" (1.0.0) by The Doggy
Errors:
sqlmatches.smx (SQLMatches): Could not find required plugin "sqlmatches_apistats"

[SM] Displaying 14 extensions:
[09] REST in Pawn (1.2.1): Provides HTTP and JSON natives for plugins

can you help me with this ?
i am using Hosted web version

**Comment by The-Doggy** [comment]
Apologies, this should be fixed with commit f897c21. Download the latest plugin version from [here](https://github.com/WardPearce/SQLMatches#sourcemod-setup).
