### ISSUE TITLE
HTTP_OnEndMatch Failed! Error After the game

### ISSUE THREAD

**Issue by rpkaul** [SQLMatches/API#20]
after game i am getting this error 

```
L 08/10/2020 - 09:24:20: [sqlmatches.smx] Event_HalfTime(): Starting team swap...
[LOTGaming] CT 3 - 0  TERRORIST
Going to intermission...
L 08/10/2020 - 09:24:49: [sqlmatches.smx] HTTP_OnEndMatch Failed! Error: 
L 08/10/2020 - 09:24:51: [sqlmatches.smx] Event_HalfTime(): Teams have already been swapped!
Completed GOTV demo "pug_de_mirage_2020-08-10_09.dem", recording time 137.2
```

**Comment by WardPearce** [comment]
we're looking into this now

**Comment by WardPearce** [comment]
Hopefully the latest push has fixed these issues, I'm currently taking a short break from open source so dev time might slow down a bit for this repo. I'll be back soon!

**Comment by WardPearce** [comment]
Whenever I get some time I'm going to re-write the plugin leaving out the SDK.

**Comment by WardPearce** [comment]
Fixed with https://github.com/WardPearce/SQLMatches/commit/f6074933cc4138453249e243f046a3ad7b2fc7bb
