### ISSUE TITLE
Error when pip3 install SQLMatches

### ISSUE THREAD

**Issue by strteamservidores** [SQLMatches/API#23]
I got this error, can you help me? (Centos 8)

![image](https://user-images.githubusercontent.com/69168702/93363802-20ba2980-f81e-11ea-9651-c34af1f9a878.png)

**Comment by WardPearce** [comment]
This might fix your issue
https://stackoverflow.com/questions/11094718/error-command-gcc-failed-with-exit-status-1-while-installing-eventlet
