### ISSUE TITLE
Error when run run.py

### ISSUE THREAD

**Issue by strteamservidores** [SQLMatches/API#29]
Hello, im getting this error when i run the run.py file

![image](https://user-images.githubusercontent.com/69168702/97064797-1870af00-157f-11eb-9aeb-7c2fd5f338b4.png)

**Comment by WardPearce** [comment]
You've entered invalid account details for B2Settings.

**Comment by strteamservidores** [comment]
where i create a B2Settings account ?

**Comment by WardPearce** [comment]
https://www.backblaze.com

You need to create a API key & give the key details in B2Settings
