### ISSUE TITLE
Hosted version can't see stats

### ISSUE THREAD

**Issue by sout12** [SQLMatches/API#32]
So using the hosted version, I see the current game being played with the score but I can't actually click on it and see player names and kills/deaths, any reason why?

**Comment by WardPearce** [comment]
Are you using the latest version of the plugin?
could you send any relevant error logs

**Comment by sout12** [comment]
I think so 
![image](https://user-images.githubusercontent.com/15899910/99155680-1c788400-2688-11eb-833c-a6ac6c1c6b22.png)
![image](https://user-images.githubusercontent.com/15899910/99155700-3dd97000-2688-11eb-8879-4e9ab5ef818b.png)

I downloaded the plugins from clicking on the link under "sourcemod setup"
And as far as error logs go I appear to have none

**Comment by WardPearce** [comment]
Are you using Get5 or Pugsetup?

**Comment by sout12** [comment]
No I'm not using either, just installed "Pugsetup" and I now can see team names on the website but I still can't click on a stat page damn. Does the match have to be over to see stats or can u see stats midgame?

**Comment by WardPearce** [comment]
Odd, I've tested the plugin on sourcemod 1.11. Maybe upgrade to sourcemod 1.11 or compile the source with 1.10

**Comment by sout12** [comment]
Okay I'll try that, but I am also testing with bots I probably should of mentioned that way before sorry, does bots not work with this or ?

**Comment by WardPearce** [comment]
the plugin won't record bots, but if you're in the server it should still record you

**Comment by sout12** [comment]
Okay okay ye I just tested with myself and it does work damn my bad, appreciate it :)

**Comment by WardPearce** [comment]
lol, allg
