### ISSUE TITLE
Implement option to add more owners in the community

### ISSUE THREAD

**Issue by crashzk** [SQLMatches/API#36]
Currently when we create a community there is no option to place more users as owner, this option would be interesting, so we can put more people with access to help with the configuration and such.

I believe that many users may not even know how to configure it on the server and such, so he can add someone he can trust to help him configure and such.

It would even be interesting if you can limit their access to some configs and tals, without access to see API and tals, access to all options except the API.

**NOTE:** The suggestion would be to even have an option to create more than one community in the same profile. Currently if I already have a community in my name and I can't create another one, I have to delete the current one.

I believe it may even be something for users who pay for the project, they are subscriptions and tals, free to have access to 3 communities and subscriptions to have access to 5 or more.

**Comment by WardPearce** [comment]
Yeah I really like the idea of assigning administrators permissions to access to the owner panel. Especially that I want to add some basic administration tools to SQLMatches.

I am planning to allow paid users to create unlimited communities.

Most likely the majority of new features for SQLMatches will be paid for, but the subscription fee won't increase above $2.50 a month.
All new features for plugins, API & frontend will remain open source too, only excluding the discord bot.
