### ISSUE TITLE
 Implement client-side language choice options

### ISSUE THREAD

**Issue by Rugal-Servidores** [SQLMatches/API#38]
The Levels Ranks - Web system uses a menu with several selectable languages, so if a customer is from another country, he chooses his language to understand the site.
It would be nice to implement this in SQLMatches.
I'll leave a picture is this menu on Levels Rankss - Web.
![Sem título](https://user-images.githubusercontent.com/75337558/107796934-be177c00-6d30-11eb-9e25-dc219d9f8356.png)

**Comment by WardPearce** [comment]
seems more like an issue for the frontend repo.
I do like the idea, wouldn't be hard to implement.
