### ISSUE TITLE
Demo too large - 50MB would not be too little for demos

### ISSUE THREAD

**Issue by crashzk** [SQLMatches/API#40]
I have a competitive server, 12 slots, 128 tickrate.

I have the following config for GOTV:
```
tv_enable "1"
tv_autorecord "0"
tv_delay "90"
tv_advertise_watchable "1"
tv_maxclients "8"
tv_allow_camera_man "1"
tv_allow_static_shots "1"
tv_snapshotrate "32"
tv_nochat "0" 
tv_timeout "45"
tv_delaymapchange "0"
tv_dispatchmode "1"
tv_relayvoice "1"
tv_transmitall "1"
```
However, most of the demos I can't download because it says that the demos are too heavy/large.

https://sqlmatches.com/c/ZKServidores/scoreboard/14a8cbaf-baed-4aee-9826-ac0848ac2010
https://sqlmatches.com/c/ZKServidores/scoreboard/91f09605-ab11-4e17-9425-003f9bfbc587

All of them were competitive in this case, maximum 30 rounds.

While my other casual servers have more than 30 rounds and download normally.

https://sqlmatches.com/c/ZKServidores/scoreboard/8e31d5be-663b-4a2d-b3ac-2adbdb5bf281
https://sqlmatches.com/c/ZKServidores/scoreboard/dd515fc2-31d7-4d38-90c3-f6f47257e900

Anything I can do to fix this? Any way to compress these .bz2 files more?

Or just with the same signature to solve.

**Comment by crashzk** [comment]
Another demo with a much higher score and I can download it normally.

https://sqlmatches.com/c/ZKServidores/scoreboard/07743911-7907-4067-a4e7-d8f5ad0c9376

**Comment by WardPearce** [comment]
Hey, try lowering your `tv_snapshotrate` to 16 instead of 32, otherwise you'll have to pay our monthly subscription to increase the max upload to 100 MB. Sadly `bz2` is the only supported compression library what supports sourcepawn currently.

In my private system we zip demos asynchronously from the api side but that wouldn't be possible for SQLMatches
