### ISSUE TITLE
Illegal Chunk Header

### ISSUE THREAD

**Issue by Shaneajm** [SQLMatches/API#41]
API Version: `0.0.13`
Python Version: `3.9.3`
OS: `Ubuntu 20.04`
Sourcemod Version: `1.10 build 6502`
RIPEXT Version: `1.2.3 and 1.2.2`

I don't know if you'll be able to assist as I know this is the old API version but long story short I'm trying to use the old API as a way to collect demos for my servers as SQLMatches is the best implementation I've seen yet. I didn't want to have to use the new version of the API as the old frontend is good for what I'm using it for.

When the plugin goes to update the match I get an error:

```
h11._util.RemoteProtocolError: illegal chunk header: bytearray(b'5368458000\x00{"team_1_name": "1", "team_2_name": "2", "team_1_side": 0, "team_2_side": 1, "team_1_score": 0, "team_2_score": 0, "map_name": "de_inferno"}\r\n')
```

Any ideas as to the cause? I've attached the full error I get below.

I should also note that I'm using this with the Retakes plugin if that could cause issues.
[error.txt](https://github.com/SQLMatches/API/files/6253442/error.txt)

**Comment by WardPearce** [comment]
I believe the error comes from `async for chunk in self.stream():`, when reading the request body we stream it in chunks. If the connection drops mid stream you'll get this error.

Also the [Edge branch](https://github.com/SQLMatches/API/tree/Edge) what I'm developing in my spare time is aiming to be more self-hosting friendly with a new frontend built off [wobsoriano/v-dashboard](https://github.com/wobsoriano/v-dashboard). So whenever this is completed I recommend updating from `0.0.13` to `1.0.0`.
